### ISSUE TITLE
Error openode deploy

### ISSUE THREAD

**Issue by kiboto** [martinlevesque/openode-cli#2]
I get error when run "openode deploy":

creating website...
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\compress-commons\lib\archivers\archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\zip-stream\index.js:157:49)
    at Zip.append (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\archiver\lib\plugins\zip.js:54:15)
    at Archiver._moduleAppend (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\archiver\lib\core.js:179:16)
    at Archiver._onQueueTask (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\archiver\lib\core.js:400:8)
    at C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\async\dist\async.js:4082:9
    at Object.process (C:\Users\LTr\AppData\Roaming\npm\node_modules\openode\node_modules\async\dist\async.js:2330:17)

**Comment by martinlevesque** [comment]
Thanks for reporting this error.

What is you Node.js version? I found this related issue https://github.com/archiverjs/node-archiver/issues/236

**Comment by kiboto** [comment]
Hi martinlevesque,
I updated source and nodejs. It work. Thanks!
