### ISSUE TITLE
CLI issue with -t -s with existing site which is not linked to the user account

### ISSUE THREAD

**Issue by martinlevesque** [martinlevesque/openode-cli#5]
`root@martin-VirtualBox:/home/martin/works/openode-hello-world-basic# openode deploy -t 5f583adc1f5397ec8299b6bee9f7b982 -s test TypeError: locations2Deploy.find is not a function at locs.filter (/root/.nvm/versions/node/v8.9.0/lib/node_modules/openode/modules/locations.js:29:31) at Array.filter (<anonymous>) at Object.getLocations2Clean (/root/.nvm/versions/node/v8.9.0/lib/node_modules/openode/modules/locations.js:28:15) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)

`

**Comment by martinlevesque** [comment]
this issue has been fixed in the latest version
